const RomData = {
	charmap: 'abdefghijkmnpqrtuyABCDEFGHJKLMNPQRSTUVWXYZ1234567890★▲◆&$%*+=<>:',
	charmap_text:
		'\u0000ぁあぃいぅうぇえぉおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとどなにぬねのはばぱひびぴふぶぷへべぺほぼぽまみむめもゃやゅゆょよらりるれろゎわをん゛゜ァアィイゥウェエォオカガキギクグケゲコゴサザシジスズセゼソゾタダチヂッツヅテデトドナニヌネノハバパヒビピフブプヘベペホボポマミムメモャヤュユョヨラリルレロヮワヲンヴ・ー～／（）『』※♪♂♀！？　☆★○●◇◆□■△▽▲▼,.!¡?¿‘’“”abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890@&-_#$%:;*+<=> àáâãäåæçèéêëìíîïðñòóôõöøœšþùúûüýÿž…ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØŒŠÞÙÚÛÜÝŸŽßＡＢＣＤＥＦＧＨＩＪＫＬＭＮＯＰＱＲＳＴＵＶＷＸＹＺａｂｃｄｅｆｇｈｉｊｋｌｍｎｏｐｑｒｓｔｕｖｗｘｙｚ',
	crc32table: [
		0, 1996959894, 3993919788, 2567524794, 124634137, 1886057615, 3915621685, 2657392035, 249268274, 2044508324,
		3772115230, 2547177864, 162941995, 2125561021, 3887607047, 2428444049, 498536548, 1789927666, 4089016648,
		2227061214, 450548861, 1843258603, 4107580753, 2211677639, 325883990, 1684777152, 4251122042, 2321926636, 335633487,
		1661365465, 4195302755, 2366115317, 997073096, 1281953886, 3579855332, 2724688242, 1006888145, 1258607687,
		3524101629, 2768942443, 901097722, 1119000684, 3686517206, 2898065728, 853044451, 1172266101, 3705015759,
		2882616665, 651767980, 1373503546, 3369554304, 3218104598, 565507253, 1454621731, 3485111705, 3099436303, 671266974,
		1594198024, 3322730930, 2970347812, 795835527, 1483230225, 3244367275, 3060149565, 1994146192, 31158534, 2563907772,
		4023717930, 1907459465, 112637215, 2680153253, 3904427059, 2013776290, 251722036, 2517215374, 3775830040,
		2137656763, 141376813, 2439277719, 3865271297, 1802195444, 476864866, 2238001368, 4066508878, 1812370925, 453092731,
		2181625025, 4111451223, 1706088902, 314042704, 2344532202, 4240017532, 1658658271, 366619977, 2362670323,
		4224994405, 1303535960, 984961486, 2747007092, 3569037538, 1256170817, 1037604311, 2765210733, 3554079995,
		1131014506, 879679996, 2909243462, 3663771856, 1141124467, 855842277, 2852801631, 3708648649, 1342533948, 654459306,
		3188396048, 3373015174, 1466479909, 544179635, 3110523913, 3462522015, 1591671054, 702138776, 2966460450,
		3352799412, 1504918807, 783551873, 3082640443, 3233442989, 3988292384, 2596254646, 62317068, 1957810842, 3939845945,
		2647816111, 81470997, 1943803523, 3814918930, 2489596804, 225274430, 2053790376, 3826175755, 2466906013, 167816743,
		2097651377, 4027552580, 2265490386, 503444072, 1762050814, 4150417245, 2154129355, 426522225, 1852507879,
		4275313526, 2312317920, 282753626, 1742555852, 4189708143, 2394877945, 397917763, 1622183637, 3604390888,
		2714866558, 953729732, 1340076626, 3518719985, 2797360999, 1068828381, 1219638859, 3624741850, 2936675148,
		906185462, 1090812512, 3747672003, 2825379669, 829329135, 1181335161, 3412177804, 3160834842, 628085408, 1382605366,
		3423369109, 3138078467, 570562233, 1426400815, 3317316542, 2998733608, 733239954, 1555261956, 3268935591,
		3050360625, 752459403, 1541320221, 2607071920, 3965973030, 1969922972, 40735498, 2617837225, 3943577151, 1913087877,
		83908371, 2512341634, 3803740692, 2075208622, 213261112, 2463272603, 3855990285, 2094854071, 198958881, 2262029012,
		4057260610, 1759359992, 534414190, 2176718541, 4139329115, 1873836001, 414664567, 2282248934, 4279200368,
		1711684554, 285281116, 2405801727, 4167216745, 1634467795, 376229701, 2685067896, 3608007406, 1308918612, 956543938,
		2808555105, 3495958263, 1231636301, 1047427035, 2932959818, 3654703836, 1088359270, 936918000, 2847714899,
		3736837829, 1202900863, 817233897, 3183342108, 3401237130, 1404277552, 615818150, 3134207493, 3453421203,
		1423857449, 601450431, 3009837614, 3294710456, 1567103746, 711928724, 3020668471, 3272380065, 1510334235, 755167117,
	],
	dungeons: [
		{
			ascending: false,
			const: 'NONE',
			floors: 0,
			name: '',
			valid: false,
		},
		{
			ascending: false,
			const: 'D001',
			floors: 3,
			name: 'Tiny Woods',
			valid: true,
		},
		{
			ascending: false,
			const: 'D002',
			floors: 5,
			name: 'Thunderwave Cave',
			valid: true,
		},
		{
			ascending: true,
			const: 'D003',
			floors: 9,
			name: 'Mt. Steel',
			valid: true,
		},
		{
			ascending: true,
			const: 'D004',
			floors: 13,
			name: 'Sinister Woods',
			valid: true,
		},
		{
			ascending: false,
			const: 'D005',
			floors: 9,
			name: 'Silent Chasm',
			valid: true,
		},
		{
			ascending: true,
			const: 'D006',
			floors: 13,
			name: 'Mt. Thunder',
			valid: true,
		},
		{
			ascending: true,
			const: 'D007',
			floors: 12,
			name: 'Great Canyon',
			valid: true,
		},
		{
			ascending: false,
			const: 'D008',
			floors: 14,
			name: 'Lapis Cave',
			valid: true,
		},
		{
			ascending: true,
			const: 'D009',
			floors: 15,
			name: 'Mt. Blaze',
			valid: true,
		},
		{
			ascending: true,
			const: 'D010',
			floors: 14,
			name: 'Frosty Forest',
			valid: true,
		},
		{
			ascending: true,
			const: 'D011',
			floors: 20,
			name: 'Mt. Freeze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D012',
			floors: 26,
			name: 'Magma Cavern',
			valid: true,
		},
		{
			ascending: true,
			const: 'D013',
			floors: 34,
			name: 'Sky Tower',
			valid: true,
		},
		{
			ascending: false,
			const: 'D014',
			floors: 4,
			name: 'Rock Path',
			valid: false,
		},
		{
			ascending: false,
			const: 'D015',
			floors: 4,
			name: 'Snow Path',
			valid: false,
		},
		{
			ascending: false,
			const: 'D016',
			floors: 4,
			name: 'Uproar Forest',
			valid: true,
		},
		{
			ascending: false,
			const: 'D017',
			floors: 19,
			name: 'Waterfall Pond',
			valid: true,
		},
		{
			ascending: true,
			const: 'D018',
			floors: 20,
			name: 'Desert Region',
			valid: true,
		},
		{
			ascending: false,
			const: 'D019',
			floors: 50,
			name: 'Southern Cavern',
			valid: true,
		},
		{
			ascending: true,
			const: 'D020',
			floors: 30,
			name: 'Wyvern Hill',
			valid: true,
		},
		{
			ascending: false,
			const: 'D021',
			floors: 15,
			name: 'Darknight Relic',
			valid: true,
		},
		{
			ascending: false,
			const: 'D022',
			floors: 11,
			name: 'Unown Relic',
			valid: true,
		},
		{
			ascending: false,
			const: 'D023',
			floors: 30,
			name: 'Grand Sea',
			valid: true,
		},
		{
			ascending: false,
			const: 'D024',
			floors: 75,
			name: 'Far-Off Sea',
			valid: true,
		},
		{
			ascending: true,
			const: 'D025',
			floors: 15,
			name: 'Howling Forest',
			valid: true,
		},
		{
			ascending: false,
			const: 'D026',
			floors: 40,
			name: 'Stormy Sea',
			valid: true,
		},
		{
			ascending: false,
			const: 'D027',
			floors: 99,
			name: 'Buried Relic',
			valid: true,
		},
		{
			ascending: false,
			const: 'D028',
			floors: 20,
			name: 'Solar Cave',
			valid: true,
		},
		{
			ascending: true,
			const: 'D029',
			floors: 30,
			name: 'Fiery Field',
			valid: true,
		},
		{
			ascending: true,
			const: 'D030',
			floors: 30,
			name: 'Lightning Field',
			valid: true,
		},
		{
			ascending: true,
			const: 'D031',
			floors: 30,
			name: 'Northwind Field',
			valid: true,
		},
		{
			ascending: true,
			const: 'D032',
			floors: 60,
			name: 'Mt. Faraway',
			valid: true,
		},
		{
			ascending: false,
			const: 'D033',
			floors: 20,
			name: 'Western Cave',
			valid: true,
		},
		{
			ascending: true,
			const: 'D034',
			floors: 25,
			name: 'Northern Range',
			valid: true,
		},
		{
			ascending: false,
			const: 'D035',
			floors: 25,
			name: 'Pitfall Valley',
			valid: true,
		},
		{
			ascending: false,
			const: 'D036',
			floors: 99,
			name: 'Wish Cave',
			valid: true,
		},
		{
			ascending: true,
			const: 'D037',
			floors: 99,
			name: 'Joyous Tower',
			valid: true,
		},
		{
			ascending: true,
			const: 'D038',
			floors: 99,
			name: 'Purity Forest',
			valid: true,
		},
		{
			ascending: false,
			const: 'D039',
			floors: 19,
			name: 'Murky Cave',
			valid: true,
		},
		{
			ascending: false,
			const: 'D040',
			floors: 99,
			name: 'Silver Trench',
			valid: true,
		},
		{
			ascending: false,
			const: 'D041',
			floors: 20,
			name: 'Meteor Cave',
			valid: false,
		},
		{
			ascending: false,
			const: 'D042',
			floors: 8,
			name: 'Oddity Cave',
			valid: true,
		},
		{
			ascending: false,
			const: 'D043',
			floors: 13,
			name: 'Remains Island',
			valid: true,
		},
		{
			ascending: false,
			const: 'D044',
			floors: 18,
			name: 'Marvelous Sea',
			valid: true,
		},
		{
			ascending: false,
			const: 'D045',
			floors: 25,
			name: 'Fantasy Strait',
			valid: true,
		},
		{
			ascending: false,
			const: 'D046',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D047',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D048',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D049',
			floors: 3,
			name: 'Tiny Woods',
			valid: false,
		},
		{
			ascending: false,
			const: 'D050',
			floors: 5,
			name: 'Thunderwave Cave',
			valid: false,
		},
		{
			ascending: false,
			const: 'D051',
			floors: 99,
			name: 'Normal Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D052',
			floors: 99,
			name: 'Fire Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D053',
			floors: 99,
			name: 'Water Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D054',
			floors: 99,
			name: 'Grass Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D055',
			floors: 99,
			name: 'Electric Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D056',
			floors: 99,
			name: 'Ice Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D057',
			floors: 99,
			name: 'Fighting Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D058',
			floors: 99,
			name: 'Ground Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D059',
			floors: 99,
			name: 'Flying Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D060',
			floors: 99,
			name: 'Psychic Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D061',
			floors: 99,
			name: 'Poison Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D062',
			floors: 99,
			name: 'Bug Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D063',
			floors: 99,
			name: 'Rock Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D064',
			floors: 99,
			name: 'Ghost Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D065',
			floors: 99,
			name: 'Dragon Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D066',
			floors: 99,
			name: 'Dark Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D067',
			floors: 99,
			name: 'Steel Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D068',
			floors: 99,
			name: 'Fairy Maze',
			valid: true,
		},
		{
			ascending: false,
			const: 'D069',
			floors: 7,
			name: 'Makuhita Dojo',
			valid: false,
		},
		{
			ascending: false,
			const: 'D070',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D071',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D072',
			floors: 12,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D073',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D074',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D075',
			floors: 99,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D076',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D077',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D078',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D079',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D080',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D081',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D082',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D083',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D084',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D085',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D086',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D087',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D088',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D089',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D090',
			floors: 2,
			name: 'Illusory Grotto',
			valid: false,
		},
		{
			ascending: false,
			const: 'D091',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D092',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D093',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D094',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D095',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D096',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D097',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D098',
			floors: 2,
			name: 'Mt. Thunder Way Point',
			valid: true,
		},
		{
			ascending: false,
			const: 'D099',
			floors: 45,
			name: '',
			valid: true,
		},
		{
			ascending: false,
			const: 'D100',
			floors: 49,
			name: '',
			valid: false,
		},
		{
			ascending: false,
			const: 'QUEST_PRIZE',
			floors: 3,
			name: 'Mt. Thunder Way Point',
			valid: false,
		},
		{
			ascending: false,
			const: 'QUEST_PRIZE_SYMBOL',
			floors: 3,
			name: 'Mt. Thunder Way Point',
			valid: false,
		},
		{
			ascending: false,
			const: 'TOWN_SHOP',
			floors: 3,
			name: 'Mt. Thunder Way Point',
			valid: false,
		},
		{
			ascending: false,
			const: 'FIXEDMAP_CHEST',
			floors: 3,
			name: 'Mt. Thunder Way Point',
			valid: false,
		},
		{
			ascending: true,
			const: 'FRIEND_RESCUE_PRIZE',
			floors: 3,
			name: 'Mt. Thunder Way Point',
			valid: false,
		},
		{
			ascending: true,
			const: 'FRIEND_RESCUE_PRIZE_SPECIAL',
			floors: 3,
			name: 'Mt. Thunder Way Point',
			valid: false,
		},
		{
			ascending: true,
			const: 'FRIEND_RESCUE_PRIZE_DELUXE',
			floors: 3,
			name: 'Mt. Thunder Way Point',
			valid: false,
		},
		{
			ascending: true,
			const: 'EVENT_PRIZE',
			floors: 3,
			name: 'Mt. Thunder Way Point',
			valid: false,
		},
		{
			ascending: true,
			const: 'TOWN_SHOP_AZUKI',
			floors: 3,
			name: 'Mt. Thunder Way Point',
			valid: false,
		},
	],
	genders: [
		{
			const: 'MALE',
			name: 'Male',
			valid: true,
		},
		{
			const: 'FEMALE',
			name: 'Female',
			valid: true,
		},
		{
			const: 'UNKNOWN',
			name: 'Unknown',
			valid: true,
		},
	],
	pokemon: [
		{
			const: 'NONE',
			name: '',
			valid: false,
		},
		{
			const: 'FUSHIGIDANE',
			name: 'Bulbasaur',
			valid: true,
		},
		{
			const: 'FUSHIGISOU',
			name: 'Ivysaur',
			valid: true,
		},
		{
			const: 'FUSHIGIBANA',
			name: 'Venusaur',
			valid: true,
		},
		{
			const: 'FUSHIGIBANA_MEGA',
			name: 'Venusaur',
			valid: false,
		},
		{
			const: 'HITOKAGE',
			name: 'Charmander',
			valid: true,
		},
		{
			const: 'RIZAADO',
			name: 'Charmeleon',
			valid: true,
		},
		{
			const: 'RIZAADON',
			name: 'Charizard',
			valid: true,
		},
		{
			const: 'RIZAADON_MEGA_X',
			name: 'Charizard',
			valid: false,
		},
		{
			const: 'RIZAADON_MEGA_Y',
			name: 'Charizard',
			valid: false,
		},
		{
			const: 'ZENIGAME',
			name: 'Squirtle',
			valid: true,
		},
		{
			const: 'KAMEERU',
			name: 'Wartortle',
			valid: true,
		},
		{
			const: 'KAMEKKUSU',
			name: 'Blastoise',
			valid: true,
		},
		{
			const: 'KAMEKKUSU_MEGA',
			name: 'Blastoise',
			valid: false,
		},
		{
			const: 'KYATAPII',
			name: 'Caterpie',
			valid: true,
		},
		{
			const: 'TORANSERU',
			name: 'Metapod',
			valid: true,
		},
		{
			const: 'BATAFURII',
			name: 'Butterfree',
			valid: true,
		},
		{
			const: 'BIIDORU',
			name: 'Weedle',
			valid: true,
		},
		{
			const: 'KOKUUN',
			name: 'Kakuna',
			valid: true,
		},
		{
			const: 'SUPIAA',
			name: 'Beedrill',
			valid: true,
		},
		{
			const: 'SUPIAA_MEGA',
			name: 'Beedrill',
			valid: false,
		},
		{
			const: 'POPPO',
			name: 'Pidgey',
			valid: true,
		},
		{
			const: 'PIJON',
			name: 'Pidgeotto',
			valid: true,
		},
		{
			const: 'PIJOTTO',
			name: 'Pidgeot',
			valid: true,
		},
		{
			const: 'PIJOTTO_MEGA',
			name: 'Pidgeot',
			valid: false,
		},
		{
			const: 'KORATTA',
			name: 'Rattata',
			valid: true,
		},
		{
			const: 'RATTA',
			name: 'Raticate',
			valid: true,
		},
		{
			const: 'ONISUZUME',
			name: 'Spearow',
			valid: true,
		},
		{
			const: 'ONIDORIRU',
			name: 'Fearow',
			valid: true,
		},
		{
			const: 'AABO',
			name: 'Ekans',
			valid: true,
		},
		{
			const: 'AABOKKU',
			name: 'Arbok',
			valid: true,
		},
		{
			const: 'PICHUU',
			name: 'Pichu',
			valid: true,
		},
		{
			const: 'PIKACHUU',
			name: 'Pikachu',
			valid: true,
		},
		{
			const: 'RAICHUU',
			name: 'Raichu',
			valid: true,
		},
		{
			const: 'SANDO',
			name: 'Sandshrew',
			valid: true,
		},
		{
			const: 'SANDOPAN',
			name: 'Sandslash',
			valid: true,
		},
		{
			const: 'NIDORAN_F',
			name: 'Nidoran♀',
			valid: true,
		},
		{
			const: 'NIDORIINA',
			name: 'Nidorina',
			valid: true,
		},
		{
			const: 'NIDOKUIN',
			name: 'Nidoqueen',
			valid: true,
		},
		{
			const: 'NIDORAN_M',
			name: 'Nidoran♂',
			valid: true,
		},
		{
			const: 'NIDORIINO',
			name: 'Nidorino',
			valid: true,
		},
		{
			const: 'NIDOKINGU',
			name: 'Nidoking',
			valid: true,
		},
		{
			const: 'PII',
			name: 'Cleffa',
			valid: true,
		},
		{
			const: 'PIPPI',
			name: 'Clefairy',
			valid: true,
		},
		{
			const: 'PIKUSHII',
			name: 'Clefable',
			valid: true,
		},
		{
			const: 'ROKON',
			name: 'Vulpix',
			valid: true,
		},
		{
			const: 'KYUUKON',
			name: 'Ninetales',
			valid: true,
		},
		{
			const: 'PUPURIN',
			name: 'Igglybuff',
			valid: true,
		},
		{
			const: 'PURIN',
			name: 'Jigglypuff',
			valid: true,
		},
		{
			const: 'PUKURIN',
			name: 'Wigglytuff',
			valid: true,
		},
		{
			const: 'ZUBATTO',
			name: 'Zubat',
			valid: true,
		},
		{
			const: 'GORUBATTO',
			name: 'Golbat',
			valid: true,
		},
		{
			const: 'KUROBATTO',
			name: 'Crobat',
			valid: true,
		},
		{
			const: 'NAZONOKUSA',
			name: 'Oddish',
			valid: true,
		},
		{
			const: 'KUSAIHANA',
			name: 'Gloom',
			valid: true,
		},
		{
			const: 'RAFURESHIA',
			name: 'Vileplume',
			valid: true,
		},
		{
			const: 'KIREIHANA',
			name: 'Bellossom',
			valid: true,
		},
		{
			const: 'PARASU',
			name: 'Paras',
			valid: true,
		},
		{
			const: 'PARASEKUTO',
			name: 'Parasect',
			valid: true,
		},
		{
			const: 'KONPAN',
			name: 'Venonat',
			valid: true,
		},
		{
			const: 'MORUFON',
			name: 'Venomoth',
			valid: true,
		},
		{
			const: 'DIGUDA',
			name: 'Diglett',
			valid: true,
		},
		{
			const: 'DAGUTORIO',
			name: 'Dugtrio',
			valid: true,
		},
		{
			const: 'NYAASU',
			name: 'Meowth',
			valid: true,
		},
		{
			const: 'PERUSHIAN',
			name: 'Persian',
			valid: true,
		},
		{
			const: 'KODAKKU',
			name: 'Psyduck',
			valid: true,
		},
		{
			const: 'GORUDAKKU',
			name: 'Golduck',
			valid: true,
		},
		{
			const: 'MANKII',
			name: 'Mankey',
			valid: true,
		},
		{
			const: 'OKORIZARU',
			name: 'Primeape',
			valid: true,
		},
		{
			const: 'GAADI',
			name: 'Growlithe',
			valid: true,
		},
		{
			const: 'UINDI',
			name: 'Arcanine',
			valid: true,
		},
		{
			const: 'NYOROMO',
			name: 'Poliwag',
			valid: true,
		},
		{
			const: 'NYOROZO',
			name: 'Poliwhirl',
			valid: true,
		},
		{
			const: 'NYOROBON',
			name: 'Poliwrath',
			valid: true,
		},
		{
			const: 'NYOROTONO',
			name: 'Politoed',
			valid: true,
		},
		{
			const: 'KEESHII',
			name: 'Abra',
			valid: true,
		},
		{
			const: 'YUNGERAA',
			name: 'Kadabra',
			valid: true,
		},
		{
			const: 'FUUDIN',
			name: 'Alakazam',
			valid: true,
		},
		{
			const: 'FUUDIN_MEGA',
			name: 'Alakazam',
			valid: false,
		},
		{
			const: 'WANRIKII',
			name: 'Machop',
			valid: true,
		},
		{
			const: 'GOORIKII',
			name: 'Machoke',
			valid: true,
		},
		{
			const: 'KAIRIKII',
			name: 'Machamp',
			valid: true,
		},
		{
			const: 'MADATSUBOMI',
			name: 'Bellsprout',
			valid: true,
		},
		{
			const: 'UTSUDON',
			name: 'Weepinbell',
			valid: true,
		},
		{
			const: 'UTSUBOTTO',
			name: 'Victreebel',
			valid: true,
		},
		{
			const: 'MENOKURAGE',
			name: 'Tentacool',
			valid: true,
		},
		{
			const: 'DOKUKURAGE',
			name: 'Tentacruel',
			valid: true,
		},
		{
			const: 'ISHITSUBUTE',
			name: 'Geodude',
			valid: true,
		},
		{
			const: 'GOROON',
			name: 'Graveler',
			valid: true,
		},
		{
			const: 'GOROONYA',
			name: 'Golem',
			valid: true,
		},
		{
			const: 'PONIITA',
			name: 'Ponyta',
			valid: true,
		},
		{
			const: 'GYAROPPU',
			name: 'Rapidash',
			valid: true,
		},
		{
			const: 'YADON',
			name: 'Slowpoke',
			valid: true,
		},
		{
			const: 'YADORAN',
			name: 'Slowbro',
			valid: true,
		},
		{
			const: 'YADORAN_MEGA',
			name: 'Slowbro',
			valid: false,
		},
		{
			const: 'YADOKINGU',
			name: 'Slowking',
			valid: true,
		},
		{
			const: 'KOIRU',
			name: 'Magnemite',
			valid: true,
		},
		{
			const: 'REAKOIRU',
			name: 'Magneton',
			valid: true,
		},
		{
			const: 'JIBAKOIRU',
			name: 'Magnezone',
			valid: true,
		},
		{
			const: 'KAMONEGI',
			name: "Farfetch'd",
			valid: true,
		},
		{
			const: 'DOODOO',
			name: 'Doduo',
			valid: true,
		},
		{
			const: 'DOODORIO',
			name: 'Dodrio',
			valid: true,
		},
		{
			const: 'PAUWAU',
			name: 'Seel',
			valid: true,
		},
		{
			const: 'JUGON',
			name: 'Dewgong',
			valid: true,
		},
		{
			const: 'BETOBETAA',
			name: 'Grimer',
			valid: true,
		},
		{
			const: 'BETOBETON',
			name: 'Muk',
			valid: true,
		},
		{
			const: 'SHERUDAA',
			name: 'Shellder',
			valid: true,
		},
		{
			const: 'PARUSHEN',
			name: 'Cloyster',
			valid: true,
		},
		{
			const: 'GOOSU',
			name: 'Gastly',
			valid: true,
		},
		{
			const: 'GOOSUTO',
			name: 'Haunter',
			valid: true,
		},
		{
			const: 'GENGAA',
			name: 'Gengar',
			valid: true,
		},
		{
			const: 'GENGAA_MEGA',
			name: 'Gengar',
			valid: false,
		},
		{
			const: 'IWAAKU',
			name: 'Onix',
			valid: true,
		},
		{
			const: 'HAGANEERU',
			name: 'Steelix',
			valid: true,
		},
		{
			const: 'HAGANEERU_MEGA',
			name: 'Steelix',
			valid: false,
		},
		{
			const: 'SURIIPU',
			name: 'Drowzee',
			valid: true,
		},
		{
			const: 'SURIIPAA',
			name: 'Hypno',
			valid: true,
		},
		{
			const: 'KURABU',
			name: 'Krabby',
			valid: true,
		},
		{
			const: 'KINGURAA',
			name: 'Kingler',
			valid: true,
		},
		{
			const: 'BIRIRIDAMA',
			name: 'Voltorb',
			valid: true,
		},
		{
			const: 'MARUMAIN',
			name: 'Electrode',
			valid: true,
		},
		{
			const: 'TAMATAMA',
			name: 'Exeggcute',
			valid: true,
		},
		{
			const: 'NASSHII',
			name: 'Exeggutor',
			valid: true,
		},
		{
			const: 'KARAKARA',
			name: 'Cubone',
			valid: true,
		},
		{
			const: 'GARAGARA',
			name: 'Marowak',
			valid: true,
		},
		{
			const: 'BARUKII',
			name: 'Tyrogue',
			valid: true,
		},
		{
			const: 'SAWAMURAA',
			name: 'Hitmonlee',
			valid: true,
		},
		{
			const: 'EBIWARAA',
			name: 'Hitmonchan',
			valid: true,
		},
		{
			const: 'KAPOERAA',
			name: 'Hitmontop',
			valid: true,
		},
		{
			const: 'BERORINGA',
			name: 'Lickitung',
			valid: true,
		},
		{
			const: 'BEROBERUTO',
			name: 'Lickilicky',
			valid: true,
		},
		{
			const: 'DOGAASU',
			name: 'Koffing',
			valid: true,
		},
		{
			const: 'MATADOGASU',
			name: 'Weezing',
			valid: true,
		},
		{
			const: 'SAIHOON',
			name: 'Rhyhorn',
			valid: true,
		},
		{
			const: 'SAIDON',
			name: 'Rhydon',
			valid: true,
		},
		{
			const: 'DOSAIDON',
			name: 'Rhyperior',
			valid: true,
		},
		{
			const: 'PINPUKU',
			name: 'Happiny',
			valid: true,
		},
		{
			const: 'RAKKII',
			name: 'Chansey',
			valid: true,
		},
		{
			const: 'HAPINASU',
			name: 'Blissey',
			valid: true,
		},
		{
			const: 'MONJARA',
			name: 'Tangela',
			valid: true,
		},
		{
			const: 'MOJANBO',
			name: 'Tangrowth',
			valid: true,
		},
		{
			const: 'GARUURA',
			name: 'Kangaskhan',
			valid: true,
		},
		{
			const: 'GARUURA_MEGA',
			name: 'Kangaskhan',
			valid: false,
		},
		{
			const: 'TATTSUU',
			name: 'Horsea',
			valid: true,
		},
		{
			const: 'SHIIDORA',
			name: 'Seadra',
			valid: true,
		},
		{
			const: 'KINGUDORA',
			name: 'Kingdra',
			valid: true,
		},
		{
			const: 'TOSAKINTO',
			name: 'Goldeen',
			valid: true,
		},
		{
			const: 'AZUMAOU',
			name: 'Seaking',
			valid: true,
		},
		{
			const: 'HITODEMAN',
			name: 'Staryu',
			valid: true,
		},
		{
			const: 'SUTAAMII',
			name: 'Starmie',
			valid: true,
		},
		{
			const: 'MANENE',
			name: 'Mime Jr.',
			valid: true,
		},
		{
			const: 'BARIYAADO',
			name: 'Mr. Mime',
			valid: true,
		},
		{
			const: 'SUTORAIKU',
			name: 'Scyther',
			valid: true,
		},
		{
			const: 'HASSAMU',
			name: 'Scizor',
			valid: true,
		},
		{
			const: 'HASSAMU_MEGA',
			name: 'Scizor',
			valid: false,
		},
		{
			const: 'MUCHUURU',
			name: 'Smoochum',
			valid: true,
		},
		{
			const: 'RUUJURA',
			name: 'Jynx',
			valid: true,
		},
		{
			const: 'EREKIDDO',
			name: 'Elekid',
			valid: true,
		},
		{
			const: 'EREBUU',
			name: 'Electabuzz',
			valid: true,
		},
		{
			const: 'EREKIBURU',
			name: 'Electivire',
			valid: true,
		},
		{
			const: 'BUBII',
			name: 'Magby',
			valid: true,
		},
		{
			const: 'BUUBAA',
			name: 'Magmar',
			valid: true,
		},
		{
			const: 'BUUBAAN',
			name: 'Magmortar',
			valid: true,
		},
		{
			const: 'KAIROSU',
			name: 'Pinsir',
			valid: true,
		},
		{
			const: 'KAIROSU_MEGA',
			name: 'Pinsir',
			valid: false,
		},
		{
			const: 'KENTAROSU',
			name: 'Tauros',
			valid: true,
		},
		{
			const: 'KOIKINGU',
			name: 'Magikarp',
			valid: true,
		},
		{
			const: 'GYARADOSU',
			name: 'Gyarados',
			valid: true,
		},
		{
			const: 'GYARADOSU_MEGA',
			name: 'Gyarados',
			valid: false,
		},
		{
			const: 'RAPURASU',
			name: 'Lapras',
			valid: true,
		},
		{
			const: 'METAMON',
			name: 'Ditto',
			valid: true,
		},
		{
			const: 'IIBUI',
			name: 'Eevee',
			valid: true,
		},
		{
			const: 'SHAWAAZU',
			name: 'Vaporeon',
			valid: true,
		},
		{
			const: 'SANDAASU',
			name: 'Jolteon',
			valid: true,
		},
		{
			const: 'BUUSUTAA',
			name: 'Flareon',
			valid: true,
		},
		{
			const: 'EEFI',
			name: 'Espeon',
			valid: true,
		},
		{
			const: 'BURAKKII',
			name: 'Umbreon',
			valid: true,
		},
		{
			const: 'RIIFIA',
			name: 'Leafeon',
			valid: true,
		},
		{
			const: 'GUREISHIA',
			name: 'Glaceon',
			valid: true,
		},
		{
			const: 'NINFIA',
			name: 'Sylveon',
			valid: true,
		},
		{
			const: 'PORIGON',
			name: 'Porygon',
			valid: true,
		},
		{
			const: 'PORIGON2',
			name: 'Porygon2',
			valid: true,
		},
		{
			const: 'PORIGONZ',
			name: 'Porygon-Z',
			valid: true,
		},
		{
			const: 'OMUNAITO',
			name: 'Omanyte',
			valid: true,
		},
		{
			const: 'OMUSUTAA',
			name: 'Omastar',
			valid: true,
		},
		{
			const: 'KABUTO',
			name: 'Kabuto',
			valid: true,
		},
		{
			const: 'KABUTOPUSU',
			name: 'Kabutops',
			valid: true,
		},
		{
			const: 'PUTERA',
			name: 'Aerodactyl',
			valid: true,
		},
		{
			const: 'PUTERA_MEGA',
			name: 'Aerodactyl',
			valid: false,
		},
		{
			const: 'GONBE',
			name: 'Munchlax',
			valid: true,
		},
		{
			const: 'KABIGON',
			name: 'Snorlax',
			valid: true,
		},
		{
			const: 'FURIIZAA',
			name: 'Articuno',
			valid: true,
		},
		{
			const: 'SANDAA',
			name: 'Zapdos',
			valid: true,
		},
		{
			const: 'FAIYAA',
			name: 'Moltres',
			valid: true,
		},
		{
			const: 'MINIRYUU',
			name: 'Dratini',
			valid: true,
		},
		{
			const: 'HAKURYUU',
			name: 'Dragonair',
			valid: true,
		},
		{
			const: 'KAIRYUU',
			name: 'Dragonite',
			valid: true,
		},
		{
			const: 'MYUUTSUU',
			name: 'Mewtwo',
			valid: true,
		},
		{
			const: 'MYUUTSUU_MEGA_X',
			name: 'Mewtwo',
			valid: false,
		},
		{
			const: 'MYUUTSUU_MEGA_Y',
			name: 'Mewtwo',
			valid: false,
		},
		{
			const: 'MYUU',
			name: 'Mew',
			valid: true,
		},
		{
			const: 'CHIKORIITA',
			name: 'Chikorita',
			valid: true,
		},
		{
			const: 'BEIRIIFU',
			name: 'Bayleef',
			valid: true,
		},
		{
			const: 'MEGANIUMU',
			name: 'Meganium',
			valid: true,
		},
		{
			const: 'HINOARASHI',
			name: 'Cyndaquil',
			valid: true,
		},
		{
			const: 'MAGUMARASHI',
			name: 'Quilava',
			valid: true,
		},
		{
			const: 'BAKUFUUN',
			name: 'Typhlosion',
			valid: true,
		},
		{
			const: 'WANINOKO',
			name: 'Totodile',
			valid: true,
		},
		{
			const: 'ARIGEITSU',
			name: 'Croconaw',
			valid: true,
		},
		{
			const: 'OODAIRU',
			name: 'Feraligatr',
			valid: true,
		},
		{
			const: 'OTACHI',
			name: 'Sentret',
			valid: true,
		},
		{
			const: 'OOTACHI',
			name: 'Furret',
			valid: true,
		},
		{
			const: 'HOOHOO',
			name: 'Hoothoot',
			valid: true,
		},
		{
			const: 'YORUNOZUKU',
			name: 'Noctowl',
			valid: true,
		},
		{
			const: 'REDIBA',
			name: 'Ledyba',
			valid: true,
		},
		{
			const: 'REDIAN',
			name: 'Ledian',
			valid: true,
		},
		{
			const: 'ITOMARU',
			name: 'Spinarak',
			valid: true,
		},
		{
			const: 'ARIADOSU',
			name: 'Ariados',
			valid: true,
		},
		{
			const: 'CHONCHII',
			name: 'Chinchou',
			valid: true,
		},
		{
			const: 'RANTAAN',
			name: 'Lanturn',
			valid: true,
		},
		{
			const: 'TOGEPII',
			name: 'Togepi',
			valid: true,
		},
		{
			const: 'TOGECHIKKU',
			name: 'Togetic',
			valid: true,
		},
		{
			const: 'TOGEKISSU',
			name: 'Togekiss',
			valid: true,
		},
		{
			const: 'NEITYI',
			name: 'Natu',
			valid: true,
		},
		{
			const: 'NEITYIO',
			name: 'Xatu',
			valid: true,
		},
		{
			const: 'MERIIPU',
			name: 'Mareep',
			valid: true,
		},
		{
			const: 'MOKOKO',
			name: 'Flaaffy',
			valid: true,
		},
		{
			const: 'DENRYUU',
			name: 'Ampharos',
			valid: true,
		},
		{
			const: 'DENRYUU_MEGA',
			name: 'Ampharos',
			valid: false,
		},
		{
			const: 'RURIRI',
			name: 'Azurill',
			valid: true,
		},
		{
			const: 'MARIRU',
			name: 'Marill',
			valid: true,
		},
		{
			const: 'MARIRURI',
			name: 'Azumarill',
			valid: true,
		},
		{
			const: 'USOHACHI',
			name: 'Bonsly',
			valid: true,
		},
		{
			const: 'USOKKII',
			name: 'Sudowoodo',
			valid: true,
		},
		{
			const: 'HANEKKO',
			name: 'Hoppip',
			valid: true,
		},
		{
			const: 'POPOKKO',
			name: 'Skiploom',
			valid: true,
		},
		{
			const: 'WATAKKO',
			name: 'Jumpluff',
			valid: true,
		},
		{
			const: 'EIPAMU',
			name: 'Aipom',
			valid: true,
		},
		{
			const: 'ETEBOOSU',
			name: 'Ambipom',
			valid: true,
		},
		{
			const: 'HIMANATTSU',
			name: 'Sunkern',
			valid: true,
		},
		{
			const: 'KIMAWARI',
			name: 'Sunflora',
			valid: true,
		},
		{
			const: 'YANYANMA',
			name: 'Yanma',
			valid: true,
		},
		{
			const: 'MEGAYANMA',
			name: 'Yanmega',
			valid: true,
		},
		{
			const: 'UPAA',
			name: 'Wooper',
			valid: true,
		},
		{
			const: 'NUOO',
			name: 'Quagsire',
			valid: true,
		},
		{
			const: 'YAMIKARASU',
			name: 'Murkrow',
			valid: true,
		},
		{
			const: 'DONKARASU',
			name: 'Honchkrow',
			valid: true,
		},
		{
			const: 'MUUMA',
			name: 'Misdreavus',
			valid: true,
		},
		{
			const: 'MUUMAAJI',
			name: 'Mismagius',
			valid: true,
		},
		{
			const: 'ANNOON_A',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_B',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_C',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_D',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_E',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_F',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_G',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_H',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_I',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_J',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_K',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_L',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_M',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_N',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_O',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_P',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_Q',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_R',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_S',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_T',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_U',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_V',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_W',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_X',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_Y',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_Z',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_EXC',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'ANNOON_QUE',
			name: 'Unown',
			valid: true,
		},
		{
			const: 'SOONANO',
			name: 'Wynaut',
			valid: true,
		},
		{
			const: 'SOONANSU',
			name: 'Wobbuffet',
			valid: true,
		},
		{
			const: 'KIRINRIKI',
			name: 'Girafarig',
			valid: true,
		},
		{
			const: 'KUNUGIDAMA',
			name: 'Pineco',
			valid: true,
		},
		{
			const: 'FORETOSU',
			name: 'Forretress',
			valid: true,
		},
		{
			const: 'NOKOTCHI',
			name: 'Dunsparce',
			valid: true,
		},
		{
			const: 'GURAIGAA',
			name: 'Gligar',
			valid: true,
		},
		{
			const: 'GURAION',
			name: 'Gliscor',
			valid: true,
		},
		{
			const: 'BURUU',
			name: 'Snubbull',
			valid: true,
		},
		{
			const: 'GURANBURU',
			name: 'Granbull',
			valid: true,
		},
		{
			const: 'HARIISEN',
			name: 'Qwilfish',
			valid: true,
		},
		{
			const: 'TSUBOTSUBO',
			name: 'Shuckle',
			valid: true,
		},
		{
			const: 'HERAKUROSU',
			name: 'Heracross',
			valid: true,
		},
		{
			const: 'HERAKUROSU_MEGA',
			name: 'Heracross',
			valid: false,
		},
		{
			const: 'NYUURA',
			name: 'Sneasel',
			valid: true,
		},
		{
			const: 'MANYUURA',
			name: 'Weavile',
			valid: true,
		},
		{
			const: 'HIMEGUMA',
			name: 'Teddiursa',
			valid: true,
		},
		{
			const: 'RINGUMA',
			name: 'Ursaring',
			valid: true,
		},
		{
			const: 'MAGUMAGGU',
			name: 'Slugma',
			valid: true,
		},
		{
			const: 'MAGUKARUGO',
			name: 'Magcargo',
			valid: true,
		},
		{
			const: 'URIMUU',
			name: 'Swinub',
			valid: true,
		},
		{
			const: 'INOMUU',
			name: 'Piloswine',
			valid: true,
		},
		{
			const: 'MANMUU',
			name: 'Mamoswine',
			valid: true,
		},
		{
			const: 'SANIIGO',
			name: 'Corsola',
			valid: true,
		},
		{
			const: 'TEPPOUO',
			name: 'Remoraid',
			valid: true,
		},
		{
			const: 'OKUTAN',
			name: 'Octillery',
			valid: true,
		},
		{
			const: 'DERIBAADO',
			name: 'Delibird',
			valid: true,
		},
		{
			const: 'TAMANTA',
			name: 'Mantyke',
			valid: true,
		},
		{
			const: 'MANTAIN',
			name: 'Mantine',
			valid: true,
		},
		{
			const: 'EAAMUDO',
			name: 'Skarmory',
			valid: true,
		},
		{
			const: 'DERUBIRU',
			name: 'Houndour',
			valid: true,
		},
		{
			const: 'HERUGAA',
			name: 'Houndoom',
			valid: true,
		},
		{
			const: 'HERUGAA_MEGA',
			name: 'Houndoom',
			valid: false,
		},
		{
			const: 'GOMAZOU',
			name: 'Phanpy',
			valid: true,
		},
		{
			const: 'DONFAN',
			name: 'Donphan',
			valid: true,
		},
		{
			const: 'ODOSHISHI',
			name: 'Stantler',
			valid: true,
		},
		{
			const: 'DOOBURU',
			name: 'Smeargle',
			valid: true,
		},
		{
			const: 'MIRUTANKU',
			name: 'Miltank',
			valid: true,
		},
		{
			const: 'RAIKOU',
			name: 'Raikou',
			valid: true,
		},
		{
			const: 'ENTEI',
			name: 'Entei',
			valid: true,
		},
		{
			const: 'SUIKUN',
			name: 'Suicune',
			valid: true,
		},
		{
			const: 'YOOGIRASU',
			name: 'Larvitar',
			valid: true,
		},
		{
			const: 'SANAGIRASU',
			name: 'Pupitar',
			valid: true,
		},
		{
			const: 'BANGIRASU',
			name: 'Tyranitar',
			valid: true,
		},
		{
			const: 'BANGIRASU_MEGA',
			name: 'Tyranitar',
			valid: false,
		},
		{
			const: 'RUGIA',
			name: 'Lugia',
			valid: true,
		},
		{
			const: 'HOUOU',
			name: 'Ho-Oh',
			valid: true,
		},
		{
			const: 'SEREBII',
			name: 'Celebi',
			valid: true,
		},
		{
			const: 'SEREBII_P',
			name: 'Celebi',
			valid: false,
		},
		{
			const: 'KIMORI',
			name: 'Treecko',
			valid: true,
		},
		{
			const: 'JUPUTORU',
			name: 'Grovyle',
			valid: true,
		},
		{
			const: 'JUKAIN',
			name: 'Sceptile',
			valid: true,
		},
		{
			const: 'JUKAIN_MEGA',
			name: 'Sceptile',
			valid: false,
		},
		{
			const: 'ACHAMO',
			name: 'Torchic',
			valid: true,
		},
		{
			const: 'WAKASHAMO',
			name: 'Combusken',
			valid: true,
		},
		{
			const: 'BASHAAMO',
			name: 'Blaziken',
			valid: true,
		},
		{
			const: 'BASHAAMO_MEGA',
			name: 'Blaziken',
			valid: false,
		},
		{
			const: 'MIZUGOROU',
			name: 'Mudkip',
			valid: true,
		},
		{
			const: 'NUMAKUROO',
			name: 'Marshtomp',
			valid: true,
		},
		{
			const: 'RAGURAAJI',
			name: 'Swampert',
			valid: true,
		},
		{
			const: 'RAGURAAJI_MEGA',
			name: 'Swampert',
			valid: false,
		},
		{
			const: 'POCHIENA',
			name: 'Poochyena',
			valid: true,
		},
		{
			const: 'GURAENA',
			name: 'Mightyena',
			valid: true,
		},
		{
			const: 'JIGUZAGUMA',
			name: 'Zigzagoon',
			valid: true,
		},
		{
			const: 'MASSUGUMA',
			name: 'Linoone',
			valid: true,
		},
		{
			const: 'KEMUSSO_KARA',
			name: 'Wurmple',
			valid: true,
		},
		{
			const: 'KEMUSSO_MAYU',
			name: 'Wurmple',
			valid: true,
		},
		{
			const: 'KARASARISU',
			name: 'Silcoon',
			valid: true,
		},
		{
			const: 'AGEHANTO',
			name: 'Beautifly',
			valid: true,
		},
		{
			const: 'MAYURUDO',
			name: 'Cascoon',
			valid: true,
		},
		{
			const: 'DOKUKEIRU',
			name: 'Dustox',
			valid: true,
		},
		{
			const: 'HASUBOO',
			name: 'Lotad',
			valid: true,
		},
		{
			const: 'HASUBURERO',
			name: 'Lombre',
			valid: true,
		},
		{
			const: 'RUNPAPPA',
			name: 'Ludicolo',
			valid: true,
		},
		{
			const: 'TANEBOO',
			name: 'Seedot',
			valid: true,
		},
		{
			const: 'KONOHANA',
			name: 'Nuzleaf',
			valid: true,
		},
		{
			const: 'DAATENGU',
			name: 'Shiftry',
			valid: true,
		},
		{
			const: 'SUBAME',
			name: 'Taillow',
			valid: true,
		},
		{
			const: 'OOSUBAME',
			name: 'Swellow',
			valid: true,
		},
		{
			const: 'KYAMOME',
			name: 'Wingull',
			valid: true,
		},
		{
			const: 'PERIPPAA',
			name: 'Pelipper',
			valid: true,
		},
		{
			const: 'RARUTOSU',
			name: 'Ralts',
			valid: true,
		},
		{
			const: 'KIRURIA',
			name: 'Kirlia',
			valid: true,
		},
		{
			const: 'SAANAITO',
			name: 'Gardevoir',
			valid: true,
		},
		{
			const: 'SAANAITO_MEGA',
			name: 'Gardevoir',
			valid: false,
		},
		{
			const: 'ERUREIDO',
			name: 'Gallade',
			valid: true,
		},
		{
			const: 'ERUREIDO_MEGA',
			name: 'Gallade',
			valid: false,
		},
		{
			const: 'AMETAMA',
			name: 'Surskit',
			valid: true,
		},
		{
			const: 'AMEMOOSU',
			name: 'Masquerain',
			valid: true,
		},
		{
			const: 'KINOKOKO',
			name: 'Shroomish',
			valid: true,
		},
		{
			const: 'KINOGASSA',
			name: 'Breloom',
			valid: true,
		},
		{
			const: 'NAMAKERO',
			name: 'Slakoth',
			valid: true,
		},
		{
			const: 'YARUKIMONO',
			name: 'Vigoroth',
			valid: true,
		},
		{
			const: 'KEKKINGU',
			name: 'Slaking',
			valid: true,
		},
		{
			const: 'TSUCHININ',
			name: 'Nincada',
			valid: true,
		},
		{
			const: 'TEKKANIN',
			name: 'Ninjask',
			valid: true,
		},
		{
			const: 'NUKENIN',
			name: 'Shedinja',
			valid: true,
		},
		{
			const: 'GONYONYO',
			name: 'Whismur',
			valid: true,
		},
		{
			const: 'DOGOOMU',
			name: 'Loudred',
			valid: true,
		},
		{
			const: 'BAKUONGU',
			name: 'Exploud',
			valid: true,
		},
		{
			const: 'MAKUNOSHITA',
			name: 'Makuhita',
			valid: true,
		},
		{
			const: 'HARITEYAMA',
			name: 'Hariyama',
			valid: true,
		},
		{
			const: 'NOZUPASU',
			name: 'Nosepass',
			valid: true,
		},
		{
			const: 'DAINOOZU',
			name: 'Probopass',
			valid: true,
		},
		{
			const: 'ENEKO',
			name: 'Skitty',
			valid: true,
		},
		{
			const: 'ENEKORORO',
			name: 'Delcatty',
			valid: true,
		},
		{
			const: 'YAMIRAMI',
			name: 'Sableye',
			valid: true,
		},
		{
			const: 'YAMIRAMI_MEGA',
			name: 'Sableye',
			valid: false,
		},
		{
			const: 'KUCHIITO',
			name: 'Mawile',
			valid: true,
		},
		{
			const: 'KUCHIITO_MEGA',
			name: 'Mawile',
			valid: false,
		},
		{
			const: 'KOKODORA',
			name: 'Aron',
			valid: true,
		},
		{
			const: 'KODORA',
			name: 'Lairon',
			valid: true,
		},
		{
			const: 'BOSUGODORA',
			name: 'Aggron',
			valid: true,
		},
		{
			const: 'BOSUGODORA_MEGA',
			name: 'Aggron',
			valid: false,
		},
		{
			const: 'ASANAN',
			name: 'Meditite',
			valid: true,
		},
		{
			const: 'CHAAREMU',
			name: 'Medicham',
			valid: true,
		},
		{
			const: 'CHAAREMU_MEGA',
			name: 'Medicham',
			valid: false,
		},
		{
			const: 'RAKURAI',
			name: 'Electrike',
			valid: true,
		},
		{
			const: 'RAIBORUTO',
			name: 'Manectric',
			valid: true,
		},
		{
			const: 'RAIBORUTO_MEGA',
			name: 'Manectric',
			valid: false,
		},
		{
			const: 'PURASURU',
			name: 'Plusle',
			valid: true,
		},
		{
			const: 'MAINAN',
			name: 'Minun',
			valid: true,
		},
		{
			const: 'BARUBIITO',
			name: 'Volbeat',
			valid: true,
		},
		{
			const: 'IRUMIIZE',
			name: 'Illumise',
			valid: true,
		},
		{
			const: 'SUBOMII',
			name: 'Budew',
			valid: true,
		},
		{
			const: 'ROZERIA',
			name: 'Roselia',
			valid: true,
		},
		{
			const: 'ROZUREIDO',
			name: 'Roserade',
			valid: true,
		},
		{
			const: 'GOKURIN',
			name: 'Gulpin',
			valid: true,
		},
		{
			const: 'MARUNOOMU',
			name: 'Swalot',
			valid: true,
		},
		{
			const: 'KIBANIA',
			name: 'Carvanha',
			valid: true,
		},
		{
			const: 'SAMEHADAA',
			name: 'Sharpedo',
			valid: true,
		},
		{
			const: 'SAMEHADAA_MEGA',
			name: 'Sharpedo',
			valid: false,
		},
		{
			const: 'HOERUKO',
			name: 'Wailmer',
			valid: true,
		},
		{
			const: 'HOERUOO',
			name: 'Wailord',
			valid: true,
		},
		{
			const: 'DONMERU',
			name: 'Numel',
			valid: true,
		},
		{
			const: 'BAKUUDA',
			name: 'Camerupt',
			valid: true,
		},
		{
			const: 'BAKUUDA_MEGA',
			name: 'Camerupt',
			valid: false,
		},
		{
			const: 'KOOTASU',
			name: 'Torkoal',
			valid: true,
		},
		{
			const: 'BANEBUU',
			name: 'Spoink',
			valid: true,
		},
		{
			const: 'BUUPIGGU',
			name: 'Grumpig',
			valid: true,
		},
		{
			const: 'PATCHIIRU',
			name: 'Spinda',
			valid: true,
		},
		{
			const: 'NAKKURAA',
			name: 'Trapinch',
			valid: true,
		},
		{
			const: 'BIBURAABA',
			name: 'Vibrava',
			valid: true,
		},
		{
			const: 'FURAIGON',
			name: 'Flygon',
			valid: true,
		},
		{
			const: 'SABONEA',
			name: 'Cacnea',
			valid: true,
		},
		{
			const: 'NOKUTASU',
			name: 'Cacturne',
			valid: true,
		},
		{
			const: 'CHIRUTTO',
			name: 'Swablu',
			valid: true,
		},
		{
			const: 'CHIRUTARISU',
			name: 'Altaria',
			valid: true,
		},
		{
			const: 'CHIRUTARISU_MEGA',
			name: 'Altaria',
			valid: false,
		},
		{
			const: 'ZANGUUSU',
			name: 'Zangoose',
			valid: true,
		},
		{
			const: 'HABUNEEKU',
			name: 'Seviper',
			valid: true,
		},
		{
			const: 'RUNATOON',
			name: 'Lunatone',
			valid: true,
		},
		{
			const: 'SORUROKKU',
			name: 'Solrock',
			valid: true,
		},
		{
			const: 'DOJOTCHI',
			name: 'Barboach',
			valid: true,
		},
		{
			const: 'NAMAZUN',
			name: 'Whiscash',
			valid: true,
		},
		{
			const: 'HEIGANI',
			name: 'Corphish',
			valid: true,
		},
		{
			const: 'SHIZARIGAA',
			name: 'Crawdaunt',
			valid: true,
		},
		{
			const: 'YAJIRON',
			name: 'Baltoy',
			valid: true,
		},
		{
			const: 'NENDOORU',
			name: 'Claydol',
			valid: true,
		},
		{
			const: 'RIRIIRA',
			name: 'Lileep',
			valid: true,
		},
		{
			const: 'YUREIDORU',
			name: 'Cradily',
			valid: true,
		},
		{
			const: 'ANOPUSU',
			name: 'Anorith',
			valid: true,
		},
		{
			const: 'AAMARUDO',
			name: 'Armaldo',
			valid: true,
		},
		{
			const: 'HINBASU',
			name: 'Feebas',
			valid: true,
		},
		{
			const: 'MIROKAROSU',
			name: 'Milotic',
			valid: true,
		},
		{
			const: 'POWARUN_NORMAL',
			name: 'Castform',
			valid: true,
		},
		{
			const: 'POWARUN_WATER',
			name: 'Castform',
			valid: false,
		},
		{
			const: 'POWARUN_FIRE',
			name: 'Castform',
			valid: false,
		},
		{
			const: 'POWARUN_ICE',
			name: 'Castform',
			valid: false,
		},
		{
			const: 'KAKUREON',
			name: 'Kecleon',
			valid: true,
		},
		{
			const: 'KAGEBOUZU',
			name: 'Shuppet',
			valid: true,
		},
		{
			const: 'JUPETTA',
			name: 'Banette',
			valid: true,
		},
		{
			const: 'JUPETTA_MEGA',
			name: 'Banette',
			valid: false,
		},
		{
			const: 'YOMAWARU',
			name: 'Duskull',
			valid: true,
		},
		{
			const: 'SAMAYOORU',
			name: 'Dusclops',
			valid: true,
		},
		{
			const: 'YONOWAARU',
			name: 'Dusknoir',
			valid: true,
		},
		{
			const: 'TOROPIUSU',
			name: 'Tropius',
			valid: true,
		},
		{
			const: 'RIISHAN',
			name: 'Chingling',
			valid: true,
		},
		{
			const: 'CHIRIIN',
			name: 'Chimecho',
			valid: true,
		},
		{
			const: 'ABUSORU',
			name: 'Absol',
			valid: true,
		},
		{
			const: 'ABUSORU_MEGA',
			name: 'Absol',
			valid: false,
		},
		{
			const: 'YUKIWARASHI',
			name: 'Snorunt',
			valid: true,
		},
		{
			const: 'ONIGOORI',
			name: 'Glalie',
			valid: true,
		},
		{
			const: 'ONIGOORI_MEGA',
			name: 'Glalie',
			valid: false,
		},
		{
			const: 'YUKIMENOKO',
			name: 'Froslass',
			valid: true,
		},
		{
			const: 'TAMAZARASHI',
			name: 'Spheal',
			valid: true,
		},
		{
			const: 'TODOGURAA',
			name: 'Sealeo',
			valid: true,
		},
		{
			const: 'TODOZERUGA',
			name: 'Walrein',
			valid: true,
		},
		{
			const: 'PAARURU',
			name: 'Clamperl',
			valid: true,
		},
		{
			const: 'HANTEERU',
			name: 'Huntail',
			valid: true,
		},
		{
			const: 'SAKURABISU',
			name: 'Gorebyss',
			valid: true,
		},
		{
			const: 'JIIRANSU',
			name: 'Relicanth',
			valid: true,
		},
		{
			const: 'RABUKASU',
			name: 'Luvdisc',
			valid: true,
		},
		{
			const: 'TATSUBEI',
			name: 'Bagon',
			valid: true,
		},
		{
			const: 'KOMORUU',
			name: 'Shelgon',
			valid: true,
		},
		{
			const: 'BOOMANDA',
			name: 'Salamence',
			valid: true,
		},
		{
			const: 'BOOMANDA_MEGA',
			name: 'Salamence',
			valid: false,
		},
		{
			const: 'DANBARU',
			name: 'Beldum',
			valid: true,
		},
		{
			const: 'METANGU',
			name: 'Metang',
			valid: true,
		},
		{
			const: 'METAGUROSU',
			name: 'Metagross',
			valid: true,
		},
		{
			const: 'METAGUROSU_MEGA',
			name: 'Metagross',
			valid: false,
		},
		{
			const: 'REJIROKKU',
			name: 'Regirock',
			valid: true,
		},
		{
			const: 'REJIAISU',
			name: 'Regice',
			valid: true,
		},
		{
			const: 'REJISUCHIRU',
			name: 'Registeel',
			valid: true,
		},
		{
			const: 'RATYIASU',
			name: 'Latias',
			valid: true,
		},
		{
			const: 'RATYIASU_MEGA',
			name: 'Latias',
			valid: false,
		},
		{
			const: 'RATYIOSU',
			name: 'Latios',
			valid: true,
		},
		{
			const: 'RATYIOSU_MEGA',
			name: 'Latios',
			valid: false,
		},
		{
			const: 'KAIOOGA',
			name: 'Kyogre',
			valid: true,
		},
		{
			const: 'KAIOOGA_SP',
			name: 'Kyogre',
			valid: false,
		},
		{
			const: 'GURAADON',
			name: 'Groudon',
			valid: true,
		},
		{
			const: 'GURAADON_SP',
			name: 'Groudon',
			valid: false,
		},
		{
			const: 'REKKUUZA',
			name: 'Rayquaza',
			valid: true,
		},
		{
			const: 'REKKUUZA_MEGA',
			name: 'Rayquaza',
			valid: false,
		},
		{
			const: 'JIRAACHI',
			name: 'Jirachi',
			valid: true,
		},
		{
			const: 'DEOKISHISU_N',
			name: 'Deoxys',
			valid: true,
		},
		{
			const: 'DEOKISHISU_D',
			name: 'Deoxys',
			valid: true,
		},
		{
			const: 'DEOKISHISU_A',
			name: 'Deoxys',
			valid: true,
		},
		{
			const: 'DEOKISHISU_S',
			name: 'Deoxys',
			valid: true,
		},
		{
			const: 'NAETORU',
			name: 'Turtwig',
			valid: false,
		},
		{
			const: 'HAYASHIGAME',
			name: 'Grotle',
			valid: false,
		},
		{
			const: 'DODAITOSU',
			name: 'Torterra',
			valid: false,
		},
		{
			const: 'HIKOZARU',
			name: 'Chimchar',
			valid: false,
		},
		{
			const: 'MOUKAZARU',
			name: 'Monferno',
			valid: false,
		},
		{
			const: 'GOUKAZARU',
			name: 'Infernape',
			valid: false,
		},
		{
			const: 'POTCHAMA',
			name: 'Piplup',
			valid: false,
		},
		{
			const: 'POTTAISHI',
			name: 'Prinplup',
			valid: false,
		},
		{
			const: 'ENPERUTO',
			name: 'Empoleon',
			valid: false,
		},
		{
			const: 'MUKKURU',
			name: 'Starly',
			valid: false,
		},
		{
			const: 'MUKUBAADO',
			name: 'Staravia',
			valid: false,
		},
		{
			const: 'MUKUHOOKU',
			name: 'Staraptor',
			valid: false,
		},
		{
			const: 'BIPPA',
			name: 'Bidoof',
			valid: false,
		},
		{
			const: 'BIIDARU',
			name: 'Bibarel',
			valid: false,
		},
		{
			const: 'KOROBOOSHI',
			name: 'Kricketot',
			valid: false,
		},
		{
			const: 'KOROTOKKU',
			name: 'Kricketune',
			valid: false,
		},
		{
			const: 'KORINKU',
			name: 'Shinx',
			valid: false,
		},
		{
			const: 'RUKUSHIO',
			name: 'Luxio',
			valid: false,
		},
		{
			const: 'RENTORAA',
			name: 'Luxray',
			valid: false,
		},
		{
			const: 'ZUGAIDOSU',
			name: 'Cranidos',
			valid: false,
		},
		{
			const: 'RAMUPARUDO',
			name: 'Rampardos',
			valid: false,
		},
		{
			const: 'TATETOPUSU',
			name: 'Shieldon',
			valid: false,
		},
		{
			const: 'TORIDEPUSU',
			name: 'Bastiodon',
			valid: false,
		},
		{
			const: 'MINOMUTCHI_GRASS',
			name: 'Burmy',
			valid: false,
		},
		{
			const: 'MINOMUTCHI_SAND',
			name: 'Burmy',
			valid: false,
		},
		{
			const: 'MINOMUTCHI_DUST',
			name: 'Burmy',
			valid: false,
		},
		{
			const: 'MINOMADAMU_GRASS',
			name: 'Wormadam',
			valid: false,
		},
		{
			const: 'MINOMADAMU_SAND',
			name: 'Wormadam',
			valid: false,
		},
		{
			const: 'MINOMADAMU_DUST',
			name: 'Wormadam',
			valid: false,
		},
		{
			const: 'GAAMEIRU',
			name: 'Mothim',
			valid: false,
		},
		{
			const: 'MITSUHANII',
			name: 'Combee',
			valid: false,
		},
		{
			const: 'BIIKUIN',
			name: 'Vespiquen',
			valid: false,
		},
		{
			const: 'PACHIRISU',
			name: 'Pachirisu',
			valid: false,
		},
		{
			const: 'BUIZERU',
			name: 'Buizel',
			valid: false,
		},
		{
			const: 'FUROOZERU',
			name: 'Floatzel',
			valid: false,
		},
		{
			const: 'CHERINBO',
			name: 'Cherubi',
			valid: false,
		},
		{
			const: 'CHERIMU_N',
			name: 'Cherrim',
			valid: false,
		},
		{
			const: 'CHERIMU_P',
			name: 'Cherrim',
			valid: false,
		},
		{
			const: 'KARANAKUSHI_E',
			name: 'Shellos',
			valid: false,
		},
		{
			const: 'KARANAKUSHI_W',
			name: 'Shellos',
			valid: false,
		},
		{
			const: 'TORITODON_E',
			name: 'Gastrodon',
			valid: false,
		},
		{
			const: 'TORITODON_W',
			name: 'Gastrodon',
			valid: false,
		},
		{
			const: 'FUWANTE',
			name: 'Drifloon',
			valid: false,
		},
		{
			const: 'FUWARAIDO',
			name: 'Drifblim',
			valid: false,
		},
		{
			const: 'MIMIRORU',
			name: 'Buneary',
			valid: false,
		},
		{
			const: 'MIMIROPPU',
			name: 'Lopunny',
			valid: false,
		},
		{
			const: 'MIMIROPPU_MEGA',
			name: 'Lopunny',
			valid: false,
		},
		{
			const: 'NYARUMAA',
			name: 'Glameow',
			valid: false,
		},
		{
			const: 'BUNYATTO',
			name: 'Purugly',
			valid: false,
		},
		{
			const: 'SUKANPUU',
			name: 'Stunky',
			valid: false,
		},
		{
			const: 'SUKATANKU',
			name: 'Skuntank',
			valid: false,
		},
		{
			const: 'DOOMIRAA',
			name: 'Bronzor',
			valid: false,
		},
		{
			const: 'DOOTAKUN',
			name: 'Bronzong',
			valid: false,
		},
		{
			const: 'PERAPPU',
			name: 'Chatot',
			valid: false,
		},
		{
			const: 'MIKARUGE',
			name: 'Spiritomb',
			valid: false,
		},
		{
			const: 'FUKAMARU',
			name: 'Gible',
			valid: false,
		},
		{
			const: 'GABAITO',
			name: 'Gabite',
			valid: false,
		},
		{
			const: 'GABURIASU',
			name: 'Garchomp',
			valid: false,
		},
		{
			const: 'GABURIASU_MEGA',
			name: 'Garchomp',
			valid: false,
		},
		{
			const: 'RIORU',
			name: 'Riolu',
			valid: true,
		},
		{
			const: 'RUKARIO',
			name: 'Lucario',
			valid: true,
		},
		{
			const: 'RUKARIO_MEGA',
			name: 'Lucario',
			valid: false,
		},
		{
			const: 'HIPOPOTASU',
			name: 'Hippopotas',
			valid: false,
		},
		{
			const: 'KABARUDON',
			name: 'Hippowdon',
			valid: false,
		},
		{
			const: 'SUKORUPI',
			name: 'Skorupi',
			valid: false,
		},
		{
			const: 'DORAPION',
			name: 'Drapion',
			valid: false,
		},
		{
			const: 'GUREGGURU',
			name: 'Croagunk',
			valid: false,
		},
		{
			const: 'DOKUROGGU',
			name: 'Toxicroak',
			valid: false,
		},
		{
			const: 'MASUKIPPA',
			name: 'Carnivine',
			valid: false,
		},
		{
			const: 'KEIKOUO',
			name: 'Finneon',
			valid: false,
		},
		{
			const: 'NEORANTO',
			name: 'Lumineon',
			valid: false,
		},
		{
			const: 'YUKIKABURI',
			name: 'Snover',
			valid: false,
		},
		{
			const: 'YUKINOOO',
			name: 'Abomasnow',
			valid: false,
		},
		{
			const: 'YUKINOOO_MEGA',
			name: 'Abomasnow',
			valid: false,
		},
		{
			const: 'ROTOMU',
			name: 'Rotom',
			valid: false,
		},
		{
			const: 'ROTOMU_HEAT',
			name: 'Rotom',
			valid: false,
		},
		{
			const: 'ROTOMU_SPIN',
			name: 'Rotom',
			valid: false,
		},
		{
			const: 'ROTOMU_FROST',
			name: 'Rotom',
			valid: false,
		},
		{
			const: 'ROTOMU_WASH',
			name: 'Rotom',
			valid: false,
		},
		{
			const: 'ROTOMU_CUT',
			name: 'Rotom',
			valid: false,
		},
		{
			const: 'YUKUSHII',
			name: 'Uxie',
			valid: false,
		},
		{
			const: 'EMURITTO',
			name: 'Mesprit',
			valid: false,
		},
		{
			const: 'AGUNOMU',
			name: 'Azelf',
			valid: false,
		},
		{
			const: 'DIARUGA',
			name: 'Dialga',
			valid: false,
		},
		{
			const: 'PARUKIA',
			name: 'Palkia',
			valid: false,
		},
		{
			const: 'HIIDORAN',
			name: 'Heatran',
			valid: false,
		},
		{
			const: 'REJIGIGASU',
			name: 'Regigigas',
			valid: false,
		},
		{
			const: 'GIRATYINA_A',
			name: 'Giratina',
			valid: false,
		},
		{
			const: 'GIRATYINA_O',
			name: 'Giratina',
			valid: false,
		},
		{
			const: 'KURESERIA',
			name: 'Cresselia',
			valid: false,
		},
		{
			const: 'FIONE',
			name: 'Phione',
			valid: false,
		},
		{
			const: 'MANAFI',
			name: 'Manaphy',
			valid: false,
		},
		{
			const: 'DAAKURAI',
			name: 'Darkrai',
			valid: false,
		},
		{
			const: 'SHEIMI_L',
			name: 'Shaymin',
			valid: false,
		},
		{
			const: 'SHEIMI_S',
			name: 'Shaymin',
			valid: false,
		},
		{
			const: 'ARUSEUSU_NORMAL',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_GRASS',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_FIRE',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_WATER',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_ELECTRIC',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_ICE',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_FIGHTING',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_POISON',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_GROUND',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_FLYING',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_PSYCHIC',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_BUG',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_ROCK',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_GHOST',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_DRAGON',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_DARK',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_STEEL',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'ARUSEUSU_FAIRY',
			name: 'Arceus',
			valid: false,
		},
		{
			const: 'BIKUTYINI',
			name: 'Victini',
			valid: false,
		},
		{
			const: 'TSUTAAJA',
			name: 'Snivy',
			valid: false,
		},
		{
			const: 'JANOBII',
			name: 'Servine',
			valid: false,
		},
		{
			const: 'JAROODA',
			name: 'Serperior',
			valid: false,
		},
		{
			const: 'POKABU',
			name: 'Tepig',
			valid: false,
		},
		{
			const: 'CHAOBUU',
			name: 'Pignite',
			valid: false,
		},
		{
			const: 'ENBUOO',
			name: 'Emboar',
			valid: false,
		},
		{
			const: 'MIJUMARU',
			name: 'Oshawott',
			valid: false,
		},
		{
			const: 'FUTACHIMARU',
			name: 'Dewott',
			valid: false,
		},
		{
			const: 'DAIKENKI',
			name: 'Samurott',
			valid: false,
		},
		{
			const: 'MINEZUMI',
			name: 'Patrat',
			valid: false,
		},
		{
			const: 'MIRUHOGGU',
			name: 'Watchog',
			valid: false,
		},
		{
			const: 'YOOTERII',
			name: 'Lillipup',
			valid: false,
		},
		{
			const: 'HAADERIA',
			name: 'Herdier',
			valid: false,
		},
		{
			const: 'MUURANDO',
			name: 'Stoutland',
			valid: false,
		},
		{
			const: 'CHORONEKO',
			name: 'Purrloin',
			valid: false,
		},
		{
			const: 'REPARUDASU',
			name: 'Liepard',
			valid: false,
		},
		{
			const: 'YANAPPU',
			name: 'Pansage',
			valid: false,
		},
		{
			const: 'YANAKKII',
			name: 'Simisage',
			valid: false,
		},
		{
			const: 'BAOPPU',
			name: 'Pansear',
			valid: false,
		},
		{
			const: 'BAOKKII',
			name: 'Simisear',
			valid: false,
		},
		{
			const: 'HIYAPPU',
			name: 'Panpour',
			valid: false,
		},
		{
			const: 'HIYAKKII',
			name: 'Simipour',
			valid: false,
		},
		{
			const: 'MUNNA',
			name: 'Munna',
			valid: false,
		},
		{
			const: 'MUSHAANA',
			name: 'Musharna',
			valid: false,
		},
		{
			const: 'MAMEPATO',
			name: 'Pidove',
			valid: false,
		},
		{
			const: 'HATOOBOOO',
			name: 'Tranquill',
			valid: false,
		},
		{
			const: 'KENHOROU',
			name: 'Unfezant',
			valid: false,
		},
		{
			const: 'SHIMAMA',
			name: 'Blitzle',
			valid: false,
		},
		{
			const: 'ZEBURAIKA',
			name: 'Zebstrika',
			valid: false,
		},
		{
			const: 'DANGORO',
			name: 'Roggenrola',
			valid: false,
		},
		{
			const: 'GANTORU',
			name: 'Boldore',
			valid: false,
		},
		{
			const: 'GIGAIASU',
			name: 'Gigalith',
			valid: false,
		},
		{
			const: 'KOROMORI',
			name: 'Woobat',
			valid: false,
		},
		{
			const: 'KOKOROMORI',
			name: 'Swoobat',
			valid: false,
		},
		{
			const: 'MOGURYUU',
			name: 'Drilbur',
			valid: false,
		},
		{
			const: 'DORYUUZU',
			name: 'Excadrill',
			valid: false,
		},
		{
			const: 'TABUNNE',
			name: 'Audino',
			valid: false,
		},
		{
			const: 'TABUNNE_MEGA',
			name: 'Audino',
			valid: false,
		},
		{
			const: 'DOKKORAA',
			name: 'Timburr',
			valid: false,
		},
		{
			const: 'DOTEKKOTSU',
			name: 'Gurdurr',
			valid: false,
		},
		{
			const: 'ROOBUSHIN',
			name: 'Conkeldurr',
			valid: false,
		},
		{
			const: 'OTAMARO',
			name: 'Tympole',
			valid: false,
		},
		{
			const: 'GAMAGARU',
			name: 'Palpitoad',
			valid: false,
		},
		{
			const: 'GAMAGEROGE',
			name: 'Seismitoad',
			valid: false,
		},
		{
			const: 'NAGEKI',
			name: 'Throh',
			valid: false,
		},
		{
			const: 'DAGEKI',
			name: 'Sawk',
			valid: false,
		},
		{
			const: 'KURUMIRU',
			name: 'Sewaddle',
			valid: false,
		},
		{
			const: 'KURUMAYU',
			name: 'Swadloon',
			valid: false,
		},
		{
			const: 'HAHAKOMORI',
			name: 'Leavanny',
			valid: false,
		},
		{
			const: 'FUSHIDE',
			name: 'Venipede',
			valid: false,
		},
		{
			const: 'HOIIGA',
			name: 'Whirlipede',
			valid: false,
		},
		{
			const: 'PENDORAA',
			name: 'Scolipede',
			valid: false,
		},
		{
			const: 'MONMEN',
			name: 'Cottonee',
			valid: false,
		},
		{
			const: 'ERUFUUN',
			name: 'Whimsicott',
			valid: false,
		},
		{
			const: 'CHURINE',
			name: 'Petilil',
			valid: false,
		},
		{
			const: 'DOREDYIA',
			name: 'Lilligant',
			valid: false,
		},
		{
			const: 'BASURAO_R',
			name: 'Basculin',
			valid: false,
		},
		{
			const: 'BASURAO_B',
			name: 'Basculin',
			valid: false,
		},
		{
			const: 'MEGUROKO',
			name: 'Sandile',
			valid: false,
		},
		{
			const: 'WARUBIRU',
			name: 'Krokorok',
			valid: false,
		},
		{
			const: 'WARUBIARU',
			name: 'Krookodile',
			valid: false,
		},
		{
			const: 'DARUMAKKA',
			name: 'Darumaka',
			valid: false,
		},
		{
			const: 'HIHIDARUMA_N',
			name: 'Darmanitan',
			valid: false,
		},
		{
			const: 'HIHIDARUMA_D',
			name: 'Darmanitan',
			valid: false,
		},
		{
			const: 'MARAKATCHI',
			name: 'Maractus',
			valid: false,
		},
		{
			const: 'ISHIZUMAI',
			name: 'Dwebble',
			valid: false,
		},
		{
			const: 'IWAPARESU',
			name: 'Crustle',
			valid: false,
		},
		{
			const: 'ZURUGGU',
			name: 'Scraggy',
			valid: false,
		},
		{
			const: 'ZURUZUKIN',
			name: 'Scrafty',
			valid: false,
		},
		{
			const: 'SHINBORAA',
			name: 'Sigilyph',
			valid: false,
		},
		{
			const: 'DESUMASU',
			name: 'Yamask',
			valid: false,
		},
		{
			const: 'DESUKAAN',
			name: 'Cofagrigus',
			valid: false,
		},
		{
			const: 'PUROTOOGA',
			name: 'Tirtouga',
			valid: false,
		},
		{
			const: 'ABAGOORA',
			name: 'Carracosta',
			valid: false,
		},
		{
			const: 'AAKEN',
			name: 'Archen',
			valid: false,
		},
		{
			const: 'AAKEOSU',
			name: 'Archeops',
			valid: false,
		},
		{
			const: 'YABUKURON',
			name: 'Trubbish',
			valid: false,
		},
		{
			const: 'DASUTODASU',
			name: 'Garbodor',
			valid: false,
		},
		{
			const: 'ZOROA',
			name: 'Zorua',
			valid: false,
		},
		{
			const: 'ZOROAAKU',
			name: 'Zoroark',
			valid: false,
		},
		{
			const: 'CHIRAAMII',
			name: 'Minccino',
			valid: false,
		},
		{
			const: 'CHIRACHIINO',
			name: 'Cinccino',
			valid: false,
		},
		{
			const: 'GOCHIMU',
			name: 'Gothita',
			valid: false,
		},
		{
			const: 'GOCHIMIRU',
			name: 'Gothorita',
			valid: false,
		},
		{
			const: 'GOCHIRUZERU',
			name: 'Gothitelle',
			valid: false,
		},
		{
			const: 'YUNIRAN',
			name: 'Solosis',
			valid: false,
		},
		{
			const: 'DABURAN',
			name: 'Duosion',
			valid: false,
		},
		{
			const: 'RANKURUSU',
			name: 'Reuniclus',
			valid: false,
		},
		{
			const: 'KOARUHII',
			name: 'Ducklett',
			valid: false,
		},
		{
			const: 'SUWANNA',
			name: 'Swanna',
			valid: false,
		},
		{
			const: 'BANIPUTCHI',
			name: 'Vanillite',
			valid: false,
		},
		{
			const: 'BANIRITCHI',
			name: 'Vanillish',
			valid: false,
		},
		{
			const: 'BAIBANIRA',
			name: 'Vanilluxe',
			valid: false,
		},
		{
			const: 'SHIKIJIKA_SPRING',
			name: 'Deerling',
			valid: false,
		},
		{
			const: 'SHIKIJIKA_SUMMER',
			name: 'Deerling',
			valid: false,
		},
		{
			const: 'SHIKIJIKA_AUTUMN',
			name: 'Deerling',
			valid: false,
		},
		{
			const: 'SHIKIJIKA_WINTER',
			name: 'Deerling',
			valid: false,
		},
		{
			const: 'MEBUKIJIKA_SPRING',
			name: 'Sawsbuck',
			valid: false,
		},
		{
			const: 'MEBUKIJIKA_SUMMER',
			name: 'Sawsbuck',
			valid: false,
		},
		{
			const: 'MEBUKIJIKA_AUTUMN',
			name: 'Sawsbuck',
			valid: false,
		},
		{
			const: 'MEBUKIJIKA_WINTER',
			name: 'Sawsbuck',
			valid: false,
		},
		{
			const: 'EMONGA',
			name: 'Emolga',
			valid: false,
		},
		{
			const: 'KABURUMO',
			name: 'Karrablast',
			valid: false,
		},
		{
			const: 'SHUBARUGO',
			name: 'Escavalier',
			valid: false,
		},
		{
			const: 'TAMAGETAKE',
			name: 'Foongus',
			valid: false,
		},
		{
			const: 'MOROBARERU',
			name: 'Amoonguss',
			valid: false,
		},
		{
			const: 'PURURIRU',
			name: 'Frillish',
			valid: false,
		},
		{
			const: 'BURUNGERU',
			name: 'Jellicent',
			valid: false,
		},
		{
			const: 'MAMANBOU',
			name: 'Alomomola',
			valid: false,
		},
		{
			const: 'BACHURU',
			name: 'Joltik',
			valid: false,
		},
		{
			const: 'DENCHURA',
			name: 'Galvantula',
			valid: false,
		},
		{
			const: 'TESSHIIDO',
			name: 'Ferroseed',
			valid: false,
		},
		{
			const: 'NATTOREI',
			name: 'Ferrothorn',
			valid: false,
		},
		{
			const: 'GIARU',
			name: 'Klink',
			valid: false,
		},
		{
			const: 'GIGIARU',
			name: 'Klang',
			valid: false,
		},
		{
			const: 'GIGIGIARU',
			name: 'Klinklang',
			valid: false,
		},
		{
			const: 'SHIBISHIRASU',
			name: 'Tynamo',
			valid: false,
		},
		{
			const: 'SHIBIBIIRU',
			name: 'Eelektrik',
			valid: false,
		},
		{
			const: 'SHIBIRUDON',
			name: 'Eelektross',
			valid: false,
		},
		{
			const: 'RIGUREE',
			name: 'Elgyem',
			valid: false,
		},
		{
			const: 'OOBEMU',
			name: 'Beheeyem',
			valid: false,
		},
		{
			const: 'HITOMOSHI',
			name: 'Litwick',
			valid: false,
		},
		{
			const: 'RANPURAA',
			name: 'Lampent',
			valid: false,
		},
		{
			const: 'SHANDERA',
			name: 'Chandelure',
			valid: false,
		},
		{
			const: 'KIBAGO',
			name: 'Axew',
			valid: false,
		},
		{
			const: 'ONONDO',
			name: 'Fraxure',
			valid: false,
		},
		{
			const: 'ONONOKUSU',
			name: 'Haxorus',
			valid: false,
		},
		{
			const: 'KUMASHUN',
			name: 'Cubchoo',
			valid: false,
		},
		{
			const: 'TSUNBEAA',
			name: 'Beartic',
			valid: false,
		},
		{
			const: 'FURIIJIO',
			name: 'Cryogonal',
			valid: false,
		},
		{
			const: 'CHOBOMAKI',
			name: 'Shelmet',
			valid: false,
		},
		{
			const: 'AGIRUDAA',
			name: 'Accelgor',
			valid: false,
		},
		{
			const: 'MAGGYO',
			name: 'Stunfisk',
			valid: false,
		},
		{
			const: 'KOJOFUU',
			name: 'Mienfoo',
			valid: false,
		},
		{
			const: 'KOJONDO',
			name: 'Mienshao',
			valid: false,
		},
		{
			const: 'KURIMUGAN',
			name: 'Druddigon',
			valid: false,
		},
		{
			const: 'GOBITTO',
			name: 'Golett',
			valid: false,
		},
		{
			const: 'GORUUGU',
			name: 'Golurk',
			valid: false,
		},
		{
			const: 'KOMATANA',
			name: 'Pawniard',
			valid: false,
		},
		{
			const: 'KIRIKIZAN',
			name: 'Bisharp',
			valid: false,
		},
		{
			const: 'BAFFURON',
			name: 'Bouffalant',
			valid: false,
		},
		{
			const: 'WASHIBON',
			name: 'Rufflet',
			valid: false,
		},
		{
			const: 'WOOGURU',
			name: 'Braviary',
			valid: false,
		},
		{
			const: 'BARUCHAI',
			name: 'Vullaby',
			valid: false,
		},
		{
			const: 'BARUJIINA',
			name: 'Mandibuzz',
			valid: false,
		},
		{
			const: 'KUITARAN',
			name: 'Heatmor',
			valid: false,
		},
		{
			const: 'AIANTO',
			name: 'Durant',
			valid: false,
		},
		{
			const: 'MONOZU',
			name: 'Deino',
			valid: false,
		},
		{
			const: 'JIHEDDO',
			name: 'Zweilous',
			valid: false,
		},
		{
			const: 'SAZANDORA',
			name: 'Hydreigon',
			valid: false,
		},
		{
			const: 'MERARUBA',
			name: 'Larvesta',
			valid: false,
		},
		{
			const: 'URUGAMOSU',
			name: 'Volcarona',
			valid: false,
		},
		{
			const: 'KOBARUON',
			name: 'Cobalion',
			valid: false,
		},
		{
			const: 'TERAKION',
			name: 'Terrakion',
			valid: false,
		},
		{
			const: 'BIRIJION',
			name: 'Virizion',
			valid: false,
		},
		{
			const: 'TORUNEROSU',
			name: 'Tornadus',
			valid: false,
		},
		{
			const: 'TORUNEROSU_R',
			name: 'Tornadus',
			valid: false,
		},
		{
			const: 'BORUTOROSU',
			name: 'Thundurus',
			valid: false,
		},
		{
			const: 'BORUTOROSU_R',
			name: 'Thundurus',
			valid: false,
		},
		{
			const: 'RESHIRAMU',
			name: 'Reshiram',
			valid: false,
		},
		{
			const: 'RESHIRAMU_N',
			name: 'Reshiram',
			valid: false,
		},
		{
			const: 'ZEKUROMU',
			name: 'Zekrom',
			valid: false,
		},
		{
			const: 'ZEKUROMU_N',
			name: 'Zekrom',
			valid: false,
		},
		{
			const: 'RANDOROSU',
			name: 'Landorus',
			valid: false,
		},
		{
			const: 'RANDOROSU_R',
			name: 'Landorus',
			valid: false,
		},
		{
			const: 'KYUREMU',
			name: 'Kyurem',
			valid: false,
		},
		{
			const: 'KYUREMU_BLACK',
			name: 'Kyurem',
			valid: false,
		},
		{
			const: 'KYUREMU_WHITE',
			name: 'Kyurem',
			valid: false,
		},
		{
			const: 'KERUDYIO',
			name: 'Keldeo',
			valid: false,
		},
		{
			const: 'KERUDYIO_K',
			name: 'Keldeo',
			valid: false,
		},
		{
			const: 'MEROETTA_V',
			name: 'Meloetta',
			valid: false,
		},
		{
			const: 'MEROETTA_S',
			name: 'Meloetta',
			valid: false,
		},
		{
			const: 'GENOSEKUTO',
			name: 'Genesect',
			valid: false,
		},
		{
			const: 'GENOSEKUTO_AQUA',
			name: 'Genesect',
			valid: false,
		},
		{
			const: 'GENOSEKUTO_INAZUMA',
			name: 'Genesect',
			valid: false,
		},
		{
			const: 'GENOSEKUTO_BLAZE',
			name: 'Genesect',
			valid: false,
		},
		{
			const: 'GENOSEKUTO_FREEZE',
			name: 'Genesect',
			valid: false,
		},
		{
			const: 'HARIMARON',
			name: 'Chespin',
			valid: false,
		},
		{
			const: 'HARIBOOGU',
			name: 'Quilladin',
			valid: false,
		},
		{
			const: 'BURIGARON',
			name: 'Chesnaught',
			valid: false,
		},
		{
			const: 'FOKKO',
			name: 'Fennekin',
			valid: false,
		},
		{
			const: 'TEERUNAA',
			name: 'Braixen',
			valid: false,
		},
		{
			const: 'MAFOKUSHII',
			name: 'Delphox',
			valid: false,
		},
		{
			const: 'KEROMATSU',
			name: 'Froakie',
			valid: false,
		},
		{
			const: 'GEKOGASHIRA',
			name: 'Frogadier',
			valid: false,
		},
		{
			const: 'GEKKOUGA',
			name: 'Greninja',
			valid: false,
		},
		{
			const: 'HORUBII',
			name: 'Bunnelby',
			valid: false,
		},
		{
			const: 'HORUUDO',
			name: 'Diggersby',
			valid: false,
		},
		{
			const: 'YAYAKOMA',
			name: 'Fletchling',
			valid: false,
		},
		{
			const: 'HINOYAKOMA',
			name: 'Fletchinder',
			valid: false,
		},
		{
			const: 'FAIAROO',
			name: 'Talonflame',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_HANAZONO',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_MIYABI',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_HYOUSETSU',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_YUKIGUNI',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_SETSUGEN',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_TAIRIKU',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_TEIEN',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_MODERN',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_MARIN',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_GUNTOU',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_KOUYA',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_SAJIN',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_TAIGA',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_SQUALL',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_SAVANNA',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_TAIYOU',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_OCEAN',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_JUNGLE',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_FANCY',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUKIMUSHI_BALL',
			name: 'Scatterbug',
			valid: false,
		},
		{
			const: 'KOFUURAI_HANAZONO',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_MIYABI',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_HYOUSETSU',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_YUKIGUNI',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_SETSUGEN',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_TAIRIKU',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_TEIEN',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_MODERN',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_MARIN',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_GUNTOU',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_KOUYA',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_SAJIN',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_TAIGA',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_SQUALL',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_SAVANNA',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_TAIYOU',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_OCEAN',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_JUNGLE',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_FANCY',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'KOFUURAI_BALL',
			name: 'Spewpa',
			valid: false,
		},
		{
			const: 'BIBIYON_HANAZONO',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_MIYABI',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_HYOUSETSU',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_YUKIGUNI',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_SETSUGEN',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_TAIRIKU',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_TEIEN',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_MODERN',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_MARIN',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_GUNTOU',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_KOUYA',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_SAJIN',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_TAIGA',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_SQUALL',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_SAVANNA',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_TAIYOU',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_OCEAN',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_JUNGLE',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_FANCY',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'BIBIYON_BALL',
			name: 'Vivillon',
			valid: false,
		},
		{
			const: 'SHISHIKO',
			name: 'Litleo',
			valid: false,
		},
		{
			const: 'KAENJISHI',
			name: 'Pyroar',
			valid: false,
		},
		{
			const: 'FURABEBE_RED',
			name: 'Flabébé',
			valid: false,
		},
		{
			const: 'FURABEBE_YELLOW',
			name: 'Flabébé',
			valid: false,
		},
		{
			const: 'FURABEBE_ORANGE',
			name: 'Flabébé',
			valid: false,
		},
		{
			const: 'FURABEBE_BLUE',
			name: 'Flabébé',
			valid: false,
		},
		{
			const: 'FURABEBE_WHITE',
			name: 'Flabébé',
			valid: false,
		},
		{
			const: 'FURABEBE_6',
			name: 'Flabébé',
			valid: false,
		},
		{
			const: 'FURAETTE_RED',
			name: 'Floette',
			valid: false,
		},
		{
			const: 'FURAETTE_YELLOW',
			name: 'Floette',
			valid: false,
		},
		{
			const: 'FURAETTE_ORANGE',
			name: 'Floette',
			valid: false,
		},
		{
			const: 'FURAETTE_BLUE',
			name: 'Floette',
			valid: false,
		},
		{
			const: 'FURAETTE_WHITE',
			name: 'Floette',
			valid: false,
		},
		{
			const: 'FURAETTE_6',
			name: 'Floette',
			valid: false,
		},
		{
			const: 'FURAAJESU_RED',
			name: 'Florges',
			valid: false,
		},
		{
			const: 'FURAAJESU_YELLOW',
			name: 'Florges',
			valid: false,
		},
		{
			const: 'FURAAJESU_ORANGE',
			name: 'Florges',
			valid: false,
		},
		{
			const: 'FURAAJESU_BLUE',
			name: 'Florges',
			valid: false,
		},
		{
			const: 'FURAAJESU_WHITE',
			name: 'Florges',
			valid: false,
		},
		{
			const: 'FURAAJESU_6',
			name: 'Florges',
			valid: false,
		},
		{
			const: 'MEEKURU',
			name: 'Skiddo',
			valid: false,
		},
		{
			const: 'GOOGOOTO',
			name: 'Gogoat',
			valid: false,
		},
		{
			const: 'YANCHAMU',
			name: 'Pancham',
			valid: false,
		},
		{
			const: 'GORONDA',
			name: 'Pangoro',
			valid: false,
		},
		{
			const: 'TORIMIAN',
			name: 'Furfrou',
			valid: false,
		},
		{
			const: 'TORIMIAN_HEART',
			name: 'Furfrou',
			valid: false,
		},
		{
			const: 'TORIMIAN_STAR',
			name: 'Furfrou',
			valid: false,
		},
		{
			const: 'TORIMIAN_DIA',
			name: 'Furfrou',
			valid: false,
		},
		{
			const: 'TORIMIAN_LADY',
			name: 'Furfrou',
			valid: false,
		},
		{
			const: 'TORIMIAN_MADAM',
			name: 'Furfrou',
			valid: false,
		},
		{
			const: 'TORIMIAN_GENTLE',
			name: 'Furfrou',
			valid: false,
		},
		{
			const: 'TORIMIAN_QUEEN',
			name: 'Furfrou',
			valid: false,
		},
		{
			const: 'TORIMIAN_KABUKI',
			name: 'Furfrou',
			valid: false,
		},
		{
			const: 'TORIMIAN_KINGDOM',
			name: 'Furfrou',
			valid: false,
		},
		{
			const: 'NYASUPAA',
			name: 'Espurr',
			valid: false,
		},
		{
			const: 'NYAONIKUSU_M',
			name: 'Meowstic',
			valid: false,
		},
		{
			const: 'NYAONIKUSU_F',
			name: 'Meowstic',
			valid: false,
		},
		{
			const: 'HITOTSUKI',
			name: 'Honedge',
			valid: false,
		},
		{
			const: 'NIDANGIRU',
			name: 'Doublade',
			valid: false,
		},
		{
			const: 'GIRUGARUDO_S',
			name: 'Aegislash',
			valid: false,
		},
		{
			const: 'GIRUGARUDO_B',
			name: 'Aegislash',
			valid: false,
		},
		{
			const: 'SHUSHUPU',
			name: 'Spritzee',
			valid: false,
		},
		{
			const: 'FUREFUWAN',
			name: 'Aromatisse',
			valid: false,
		},
		{
			const: 'PEROPPAFU',
			name: 'Swirlix',
			valid: false,
		},
		{
			const: 'PERORIIMU',
			name: 'Slurpuff',
			valid: false,
		},
		{
			const: 'MAAIIKA',
			name: 'Inkay',
			valid: false,
		},
		{
			const: 'KARAMANERO',
			name: 'Malamar',
			valid: false,
		},
		{
			const: 'KAMETETE',
			name: 'Binacle',
			valid: false,
		},
		{
			const: 'GAMENODESU',
			name: 'Barbaracle',
			valid: false,
		},
		{
			const: 'KUZUMOO',
			name: 'Skrelp',
			valid: false,
		},
		{
			const: 'DORAMIDORO',
			name: 'Dragalge',
			valid: false,
		},
		{
			const: 'UDEPPOU',
			name: 'Clauncher',
			valid: false,
		},
		{
			const: 'BUROSUTAA',
			name: 'Clawitzer',
			valid: false,
		},
		{
			const: 'ERIKITERU',
			name: 'Helioptile',
			valid: false,
		},
		{
			const: 'EREZAADO',
			name: 'Heliolisk',
			valid: false,
		},
		{
			const: 'CHIGORASU',
			name: 'Tyrunt',
			valid: false,
		},
		{
			const: 'GACHIGORASU',
			name: 'Tyrantrum',
			valid: false,
		},
		{
			const: 'AMARUSU',
			name: 'Amaura',
			valid: false,
		},
		{
			const: 'AMARURUGA',
			name: 'Aurorus',
			valid: false,
		},
		{
			const: 'RUCHABURU',
			name: 'Hawlucha',
			valid: false,
		},
		{
			const: 'DEDENNE',
			name: 'Dedenne',
			valid: false,
		},
		{
			const: 'MERESHII',
			name: 'Carbink',
			valid: false,
		},
		{
			const: 'NUMERA',
			name: 'Goomy',
			valid: false,
		},
		{
			const: 'NUMEIRU',
			name: 'Sliggoo',
			valid: false,
		},
		{
			const: 'NUMERUGON',
			name: 'Goodra',
			valid: false,
		},
		{
			const: 'KUREFFI',
			name: 'Klefki',
			valid: false,
		},
		{
			const: 'BOKUREE',
			name: 'Phantump',
			valid: false,
		},
		{
			const: 'OOROTTO',
			name: 'Trevenant',
			valid: false,
		},
		{
			const: 'BAKETCHA_M',
			name: 'Pumpkaboo',
			valid: false,
		},
		{
			const: 'BAKETCHA_S',
			name: 'Pumpkaboo',
			valid: false,
		},
		{
			const: 'BAKETCHA_L',
			name: 'Pumpkaboo',
			valid: false,
		},
		{
			const: 'BAKETCHA_LL',
			name: 'Pumpkaboo',
			valid: false,
		},
		{
			const: 'PANPUJIN_M',
			name: 'Gourgeist',
			valid: false,
		},
		{
			const: 'PANPUJIN_S',
			name: 'Gourgeist',
			valid: false,
		},
		{
			const: 'PANPUJIN_L',
			name: 'Gourgeist',
			valid: false,
		},
		{
			const: 'PANPUJIN_LL',
			name: 'Gourgeist',
			valid: false,
		},
		{
			const: 'KACHIKOORU',
			name: 'Bergmite',
			valid: false,
		},
		{
			const: 'KUREBEESU',
			name: 'Avalugg',
			valid: false,
		},
		{
			const: 'ONBATTO',
			name: 'Noibat',
			valid: false,
		},
		{
			const: 'ONBAAN',
			name: 'Noivern',
			valid: false,
		},
		{
			const: 'ZERUNEASU',
			name: 'Xerneas',
			valid: false,
		},
		{
			const: 'ZERUNEASU_R',
			name: 'Xerneas',
			valid: false,
		},
		{
			const: 'IBERUTARU',
			name: 'Yveltal',
			valid: false,
		},
		{
			const: 'JIGARUDE',
			name: 'Zygarde',
			valid: false,
		},
		{
			const: 'DIANSHII',
			name: 'Diancie',
			valid: false,
		},
		{
			const: 'DIANSHII_MEGA',
			name: 'Diancie',
			valid: false,
		},
		{
			const: 'FUUPA',
			name: 'Hoopa',
			valid: false,
		},
		{
			const: 'FUUPA_MEGA',
			name: 'Hoopa',
			valid: false,
		},
		{
			const: 'YOBI_01',
			name: 'Butterfree',
			valid: true,
		},
		{
			const: 'YOBI_02',
			name: 'Ninetales',
			valid: true,
		},
		{
			const: 'YOBI_03',
			name: 'Rapidash',
			valid: true,
		},
		{
			const: 'YOBI_04',
			name: 'Electrode',
			valid: true,
		},
		{
			const: 'YOBI_05',
			name: 'Exeggcute',
			valid: true,
		},
		{
			const: 'YOBI_06',
			name: 'Exeggutor',
			valid: true,
		},
		{
			const: 'YOBI_07',
			name: 'Lickilicky',
			valid: true,
		},
		{
			const: 'YOBI_08',
			name: 'Starmie',
			valid: true,
		},
		{
			const: 'YOBI_09',
			name: 'Magikarp',
			valid: true,
		},
		{
			const: 'YOBI_10',
			name: 'Gyarados',
			valid: true,
		},
		{
			const: 'YOBI_11',
			name: 'Gyarados',
			valid: false,
		},
		{
			const: 'YOBI_12',
			name: 'Ditto',
			valid: true,
		},
		{
			const: 'YOBI_13',
			name: 'Espeon',
			valid: true,
		},
		{
			const: 'YOBI_14',
			name: 'Dragonite',
			valid: true,
		},
		{
			const: 'YOBI_15',
			name: 'Hoothoot',
			valid: true,
		},
		{
			const: 'YOBI_16',
			name: 'Noctowl',
			valid: true,
		},
		{
			const: 'YOBI_17',
			name: 'Ampharos',
			valid: true,
		},
		{
			const: 'YOBI_18',
			name: 'Ampharos',
			valid: false,
		},
		{
			const: 'YOBI_19',
			name: 'Azumarill',
			valid: true,
		},
		{
			const: 'YOBI_20',
			name: 'Sudowoodo',
			valid: true,
		},
		{
			const: 'YOBI_21',
			name: 'Aipom',
			valid: true,
		},
		{
			const: 'YOBI_22',
			name: 'Ambipom',
			valid: true,
		},
		{
			const: 'YOBI_23',
			name: 'Wobbuffet',
			valid: true,
		},
		{
			const: 'YOBI_24',
			name: 'Shuckle',
			valid: true,
		},
		{
			const: 'YOBI_25',
			name: 'Corsola',
			valid: true,
		},
		{
			const: 'YOBI_26',
			name: 'Ho-Oh',
			valid: false,
		},
		{
			const: 'YOBI_27',
			name: 'Celebi',
			valid: true,
		},
		{
			const: 'YOBI_28',
			name: 'Spinda',
			valid: true,
		},
		{
			const: 'YOBI_29',
			name: 'Altaria',
			valid: true,
		},
		{
			const: 'YOBI_30',
			name: 'Altaria',
			valid: false,
		},
		{
			const: 'YOBI_31',
			name: 'Zangoose',
			valid: true,
		},
		{
			const: 'YOBI_32',
			name: 'Metagross',
			valid: true,
		},
		{
			const: 'YOBI_33',
			name: 'Metagross',
			valid: false,
		},
		{
			const: 'YOBI_34',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_35',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_36',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_37',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_38',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_39',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_40',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_41',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_42',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_43',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_44',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_45',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_46',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_47',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_48',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_49',
			name: '',
			valid: false,
		},
		{
			const: 'YOBI_50',
			name: 'Rayquaza',
			valid: false,
		},
		{
			const: 'REKKUUZA_BOSS',
			name: 'Rayquaza',
			valid: false,
		},
		{
			const: 'KAKUREON_AZUKI',
			name: 'Kecleon',
			valid: false,
		},
		{
			const: 'GARUURA_CHILD',
			name: 'Kangaskhan',
			valid: false,
		},
		{
			const: 'MIGAWARI',
			name: 'Substitute',
			valid: false,
		},
		{
			const: 'WANTED_LV',
			name: 'Outlaw Level',
			valid: false,
		},
		{
			const: 'WANTED_HP',
			name: 'Outlaw Bottom Up HP',
			valid: false,
		},
		{
			const: 'KYUREMU_BN',
			name: 'Black Kyurem',
			valid: false,
		},
		{
			const: 'KYUREMU_WN',
			name: 'White Kyurem',
			valid: false,
		},
	],
	rewards: [
		{
			const: 'NONE',
			name: '',
			valid: false,
		},
		{
			const: 'REGULAR',
			name: 'Regular',
			valid: true,
		},
		{
			const: 'SPECIAL',
			name: 'Special',
			valid: true,
		},
		{
			const: 'DELUXE',
			name: 'Deluxe',
			valid: true,
		},
	],
};
export default RomData;
